services:
  frontend:
    env_file: ".env.local"  
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  
    depends_on:
      - backend
    networks:
      - diploma-network

  backend:
    env_file: ".env.local"  
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9000:3000"
    networks:
      - diploma-network
    restart: unless-stopped

networks:
  diploma-network:
    driver: bridge